name: "Continuous Integration"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.14.x, 1.15.x ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    name: ${{ matrix.platform }} @ Go ${{ matrix.go-version }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set environment
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
          git config --global user.name "Github Action"
          git config --global user.email "noreply@github.com"
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          go get -v github.com/golang/mock/mockgen@v1.4.4

      - name: Lint source code
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Test
        run: |
          go generate ./...
          go test ./...

      - name: Update go report card
        if: success() && matrix.platform == 'ubuntu-latest'
        continue-on-error: true
        uses: creekorful/goreportcard-action@v1.0